Mliestone1: Capstone project
abdessalem1998/Capstone-project-module-1 pull request #1
Opened 2021-11-22 09:47 UTC by abdessalem1998

In this pull request firstly i use it to check if the github actions checker are set correctly and later for submitting for review for my work for an event in Electronics student club open code workshop.

2021-11-26 14:00 UTC, VanessaAoki requested changes
## STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @abdessalem1998, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Your README file looks very professional and the PR has a descriptive title/summary of the implemented changes :memo: 
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 14:00 UTC, VanessaAoki commented on README.md
> +![gif for desktop view](./content/recording-d.gif)<br />
- [ ] I think your pathing is not right, making your links break, you should consider fixing them.

![image](https://user-images.githubusercontent.com/66967274/143586728-9cda35b7-6084-41d8-940e-0ad9eb0aa4a7.png)

2021-11-26 14:00 UTC, VanessaAoki commented on README.md
> +https://www.loom.com/share/aca38f9442d94e5bb254d86966ea9ca2
- [ ] Great job making the video, I believe there is an audio issue though, I couldn't hear anything you presented, could you please re-upload it?

2021-11-26 14:00 UTC, VanessaAoki commented on scripts.js
> +}];
- [ ] Great job implementing this in such a smart way. But in order to match the original design better, you should consider adding 2 more speakers.

2021-11-26 14:00 UTC, VanessaAoki commented on style.css
> +body {
- [ ] One of the requirements for this project was to keep the styles as close to the original as possible, so you should consider using the provided fonts in this project. They are:

![image](https://user-images.githubusercontent.com/66967274/143589871-a66b6b4f-17c5-4ab1-8ecb-1f615d586c79.png)

2021-11-26 14:00 UTC, VanessaAoki commented on index.html
> +          <a class="navbar-brand text-light ps-5 ms-5 d-md-block d-none" href="index.html"><img src="images-icons/images/logo.png" class="nav-logo" alt="twitter"></a>
- [ ] Your logo is currently broken, I believe you have a pathing issue, this is what it looks like:

![image](https://user-images.githubusercontent.com/66967274/143590158-72e91bc0-6fb9-4be5-addc-f1faa1767146.png)

- [ ] I believe that not having the logo is also breaking your design since the "ISC Club" button is overflowing the header. You should consider re-checking the design once the logo is fixed.
- [ ] Beware that the same thing happens in the about page.

2021-11-26 14:00 UTC, VanessaAoki commented on index.html
> +          <img src="images-icons/images/logo.png" class="nav-icon footer-logo" alt="logo">
- [ ] Just like in the header, your logo here is also broken, it's also broken in the about page.

![image](https://user-images.githubusercontent.com/66967274/143590557-47f0d48d-4d8f-4ead-9250-a82a91106ab1.png)

2021-11-26 14:00 UTC, VanessaAoki commented on about.html
> +        <img src="images-icons/images/logo.png" id="logo-logo" class="nav-icon border px-5" alt="logo">
- [ ] Just like in the header, your logo is broken.

![image](https://user-images.githubusercontent.com/66967274/143590878-886d30d3-bfa7-4f54-83f5-d166a4bb251a.png)

2021-11-26 14:00 UTC, VanessaAoki commented on about.html
> +    </section>
- [ ] Currently, your about me page is also displaying the featured speakers, to match the original design better, you should consider removing it.

![image](https://user-images.githubusercontent.com/66967274/143591136-1c24bbf2-793f-415d-99c4-723b6d4f5068.png)

2021-11-26 14:00 UTC, VanessaAoki commented on about.html
> +        </div>
- [ ] in the desktop version, the partners section should not be visible, only in the mobile version.
- [ ] Also, in the desktop version, the footer has a dark background, the white one should only be for the mobile version.

Original design:
![image](https://user-images.githubusercontent.com/66967274/143591445-3b761c54-334c-4b92-a094-a426d3caf746.png)

2021-11-26 14:00 UTC, VanessaAoki commented on index.html
> +      <div class="upper-footer row d-flex justify-content-center">
- [ ] The partners section in the mobile version is currently broken, you should consider reviewing your mobile styles:

![image](https://user-images.githubusercontent.com/66967274/143591811-5458cc0b-1f98-45ed-9a6f-5da1b61a6417.png)

2021-11-26 14:00 UTC, VanessaAoki commented on index.html
> +      <nav class="navbar navbar-expand-md navbar-light border-md-none bg-white border-bottom">
- [ ] Your header menu is not working for the mobile version, it shows up below the main content, you should consider maybe adding a background and setting a higher z-index.

Your design:
![image](https://user-images.githubusercontent.com/66967274/143592034-28b4ca1f-fec3-4533-ab32-90e6633348d1.png)

2021-11-27 01:00 UTC, descholar-ceo approved these changes
Hi @abdessalem1998 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 01:02 UTC, merged